services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/dev/shm
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - back
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    networks:
      - back
    ports:
      - 8080:8080

  api:
    image: ghcr.io/emeric-sauthier/tp-devops-server:main
    networks:
      - back
    ports:
      - 3000:3000
    volumes:
      - ./server/src/:/app/src
    depends_on:
      - db

networks:
  back:
    name: back

volumes:
  db-data: