services:

  front:
    build: ./client/
    networks:
      - front
    ports:
      - 5173:5173
    volumes:
      - ./client/src/:/app/src
    depends_on:
      - api

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - db-data:/dev/shm
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    networks:
      - back
    ports:
      - 8080:8080

  api:
    build: ./server/
    networks:
      - back
      - front
    ports:
      - 3000:3000
    volumes:
      - ./server/src/:/app/src
    depends_on:
      db:
        condition: service_healthy

networks:
  back:
  front:

volumes:
  db-data: