# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    container_name: database
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - db-data:/dev/shm
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - back

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - back
    ports:
      - 8080:8080

  api:
    image: api:v1
    container_name: api
    networks:
      - back
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app

networks:
  back:
    name: back

volumes:
  db-data: