name: Backend - Build and Push

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  
jobs:

  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: "!.github/**"
          # if-these-paths-change-return-all-included-paths: "server/**, client/**"

      - name: Log Changed Directories
        run: echo "Changed directories ${{ steps.detect.outputs.changed }}"

  build-and-push:
    needs: detect-directory-changes
    if: ${{ needs.detect-directory-changes.outputs.changed != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker - ${{ matrix.project }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.project }}
        tags: |
          type=sha
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=raw,value=latest

    - name: Build and push Docker image - ${{ matrix.project }}
      id: push
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.project }}/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation - ${{ matrix.project }}
      uses: actions/attest@v4
      with:
        subject-name: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.project }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
