name: Backend - Build and Push

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  
jobs:

  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set-matrix.outputs.projects }}

    steps:
      - uses: actions/checkout@v4

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
      
      - name: Convert to list
        id: set-matrix
        run: |
          projects=()

          if [[ "${{ steps.filter.outputs.server }}" == "true" ]]; then
            projects+=("\"server\"")
          fi

          if [[ "${{ steps.filter.outputs.client }}" == "true" ]]; then
            projects+=("\"client\"")
          fi

          json=$(printf '[%s]' "$(IFS=,; echo "${projects[*]}")")

          echo "projects=$json" >> $GITHUB_OUTPUT
          echo "Detected projects: $json"

  versioning:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changed != '[]' }}
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log versioning result
        run: |
          echo "New release version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "Was a new release published? ${{ steps.semantic.outputs.new_release_published }}"

  build-and-push:
    needs: versioning
    if: ${{ needs.versioning.outputs.new_release_published == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-changes.outputs.changed) }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker - ${{ matrix.project }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.project }}
        tags: |
          type=sha
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=raw,value=latest

    - name: Build and push Docker image - ${{ matrix.project }}
      id: push
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.project }}/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation - ${{ matrix.project }}
      uses: actions/attest@v4
      with:
        subject-name: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.project }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
